packageExtensions:
  eslint-config-react-app@*:
    dependencies:
      '@babel/plugin-syntax-flow': ^7.16.7
      '@babel/plugin-transform-react-jsx': ^7.17.3
  react-dev-utils@*:
    dependencies:
      typescript: ^4.5.5
      webpack: ^5.69.1
  react-scripts@*:
    dependencies:
      autoprefixer: ^10.4.2

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.2.0.cjs
